import bcrypt from "bcryptjs";
import { Currency, Prisma, TransactionDirection, WorkspaceRole } from "../generated/prisma/client";
import prisma from "./prisma";

const DEV_PASSWORD = "password123";

const d = (value: string | number) => new Prisma.Decimal(value);

/**
 * Development-only password hash.
 *
 * Replace these hashes with values generated by the same hashing library
 * used by your application.
 *
 * For example, if your app uses bcrypt/argon2, generate the hash here
 * instead of storing a plain password.
 */
function dateAt(year: number, month: number, day: number, hour = 12): Date {
  // Using UTC keeps seeded timestamps deterministic across machines.
  return new Date(Date.UTC(year, month - 1, day, hour, 0, 0));
}

function monthsAgo(months: number, day: number, hour = 12): Date {
  const now = new Date();

  return dateAt(now.getUTCFullYear(), now.getUTCMonth() + 1 - months, day, hour);
}

async function main() {
  console.log("🌱 Seeding database...");

  const DEV_PASSWORD_HASH = await bcrypt.hash(DEV_PASSWORD, 12);

  // ---------------------------------------------------------------------------
  // Users
  // ---------------------------------------------------------------------------

  const alex = await prisma.user.upsert({
    where: {
      email: "alex@example.com",
    },
    update: {
      passwordHash: DEV_PASSWORD_HASH,
    },
    create: {
      email: "alex@example.com",
      passwordHash: DEV_PASSWORD_HASH,
    },
  });

  const maria = await prisma.user.upsert({
    where: {
      email: "maria@example.com",
    },
    update: {
      passwordHash: DEV_PASSWORD_HASH,
    },
    create: {
      email: "maria@example.com",
      passwordHash: DEV_PASSWORD_HASH,
    },
  });

  // ---------------------------------------------------------------------------
  // Workspaces
  // ---------------------------------------------------------------------------

  // Since Workspace.name isn't unique, use deterministic IDs for seed records.
  const personalWorkspace = await prisma.workspace.upsert({
    where: {
      id: "seed-personal-workspace",
    },
    update: {
      name: "Alex Personal",
      currency: Currency.EUR,
    },
    create: {
      id: "seed-personal-workspace",
      name: "Alex Personal",
      currency: Currency.EUR,
    },
  });

  const householdWorkspace = await prisma.workspace.upsert({
    where: {
      id: "seed-household-workspace",
    },
    update: {
      name: "Household",
      currency: Currency.EUR,
    },
    create: {
      id: "seed-household-workspace",
      name: "Household",
      currency: Currency.EUR,
    },
  });

  // ---------------------------------------------------------------------------
  // Memberships
  // ---------------------------------------------------------------------------

  await prisma.userWorkspace.upsert({
    where: {
      userId_workspaceId: {
        userId: alex.id,
        workspaceId: personalWorkspace.id,
      },
    },
    update: {
      role: WorkspaceRole.ADMIN,
    },
    create: {
      userId: alex.id,
      workspaceId: personalWorkspace.id,
      role: WorkspaceRole.ADMIN,
    },
  });

  await prisma.userWorkspace.upsert({
    where: {
      userId_workspaceId: {
        userId: alex.id,
        workspaceId: householdWorkspace.id,
      },
    },
    update: {
      role: WorkspaceRole.ADMIN,
    },
    create: {
      userId: alex.id,
      workspaceId: householdWorkspace.id,
      role: WorkspaceRole.ADMIN,
    },
  });

  await prisma.userWorkspace.upsert({
    where: {
      userId_workspaceId: {
        userId: maria.id,
        workspaceId: householdWorkspace.id,
      },
    },
    update: {
      role: WorkspaceRole.MEMBER,
    },
    create: {
      userId: maria.id,
      workspaceId: householdWorkspace.id,
      role: WorkspaceRole.MEMBER,
    },
  });

  // ---------------------------------------------------------------------------
  // Helper: transaction type
  // ---------------------------------------------------------------------------

  async function transactionType(workspaceId: string, name: string, direction: TransactionDirection) {
    return prisma.transactionType.upsert({
      where: {
        workspaceId_name: {
          workspaceId,
          name,
        },
      },
      update: {
        direction,
      },
      create: {
        workspaceId,
        name,
        direction,
      },
    });
  }

  async function category(transactionTypeId: number, name: string, description?: string) {
    return prisma.transactionCategory.upsert({
      where: {
        transactionTypeId_name: {
          transactionTypeId,
          name,
        },
      },
      update: {
        description,
      },
      create: {
        transactionTypeId,
        name,
        description,
      },
    });
  }

  async function wallet(workspaceId: string, name: string) {
    return prisma.wallet.upsert({
      where: {
        workspaceId_name: {
          workspaceId,
          name,
        },
      },
      update: {},
      create: {
        workspaceId,
        name,
      },
    });
  }

  // ===========================================================================
  // PERSONAL WORKSPACE
  // ===========================================================================

  // ---------------------------------------------------------------------------
  // Wallets
  // ---------------------------------------------------------------------------

  const personalBank = await wallet(personalWorkspace.id, "Main Bank Account");

  const personalCash = await wallet(personalWorkspace.id, "Cash");

  const personalSavings = await wallet(personalWorkspace.id, "Savings");

  const personalCreditCard = await wallet(personalWorkspace.id, "Credit Card");

  // ---------------------------------------------------------------------------
  // Transaction types
  // ---------------------------------------------------------------------------

  const personalEmployment = await transactionType(personalWorkspace.id, "Employment", TransactionDirection.INCOME);

  const personalOtherIncome = await transactionType(personalWorkspace.id, "Other Income", TransactionDirection.INCOME);

  const personalHousing = await transactionType(personalWorkspace.id, "Housing", TransactionDirection.EXPENSE);

  const personalFood = await transactionType(personalWorkspace.id, "Food", TransactionDirection.EXPENSE);

  const personalTransportation = await transactionType(
    personalWorkspace.id,
    "Transportation",
    TransactionDirection.EXPENSE,
  );

  const personalLifestyle = await transactionType(personalWorkspace.id, "Lifestyle", TransactionDirection.EXPENSE);

  const personalHealth = await transactionType(personalWorkspace.id, "Health", TransactionDirection.EXPENSE);

  const personalFinancial = await transactionType(personalWorkspace.id, "Financial", TransactionDirection.EXPENSE);

  // ---------------------------------------------------------------------------
  // Categories
  // ---------------------------------------------------------------------------

  const salary = await category(personalEmployment.id, "Salary", "Primary employment income");

  const bonus = await category(personalEmployment.id, "Bonus", "Employment bonuses and incentives");

  const freelance = await category(personalOtherIncome.id, "Freelance", "Freelance and side-project income");

  const interest = await category(personalOtherIncome.id, "Interest", "Interest and similar financial income");

  const rent = await category(personalHousing.id, "Rent", "Monthly housing rent");

  const utilities = await category(personalHousing.id, "Utilities", "Electricity, water and other utilities");

  const groceries = await category(personalFood.id, "Groceries", "Supermarket and grocery purchases");

  const dining = await category(personalFood.id, "Dining Out", "Restaurants, cafés and takeaway");

  const fuel = await category(personalTransportation.id, "Fuel");

  const publicTransport = await category(personalTransportation.id, "Public Transport");

  const taxi = await category(personalTransportation.id, "Taxi");

  const entertainment = await category(personalLifestyle.id, "Entertainment");

  const shopping = await category(personalLifestyle.id, "Shopping");

  const subscriptions = await category(personalLifestyle.id, "Subscriptions");

  const travel = await category(personalLifestyle.id, "Travel");

  const pharmacy = await category(personalHealth.id, "Pharmacy");

  const doctor = await category(personalHealth.id, "Doctor");

  const bankFees = await category(personalFinancial.id, "Bank Fees");

  // ===========================================================================
  // HOUSEHOLD WORKSPACE
  // ===========================================================================

  const householdJoint = await wallet(householdWorkspace.id, "Joint Account");

  const householdCash = await wallet(householdWorkspace.id, "Household Cash");

  const householdSavings = await wallet(householdWorkspace.id, "Emergency Fund");

  const householdIncome = await transactionType(householdWorkspace.id, "Household Income", TransactionDirection.INCOME);

  const householdHousing = await transactionType(householdWorkspace.id, "Home", TransactionDirection.EXPENSE);

  const householdFood = await transactionType(householdWorkspace.id, "Food", TransactionDirection.EXPENSE);

  const householdBills = await transactionType(householdWorkspace.id, "Bills", TransactionDirection.EXPENSE);

  const householdOther = await transactionType(householdWorkspace.id, "Other", TransactionDirection.EXPENSE);

  const contribution = await category(householdIncome.id, "Contribution", "Money contributed to household expenses");

  const householdRent = await category(householdHousing.id, "Rent");

  const householdGroceries = await category(householdFood.id, "Groceries");

  const electricity = await category(householdBills.id, "Electricity");

  const internet = await category(householdBills.id, "Internet");

  const householdSupplies = await category(householdOther.id, "Household Supplies");

  const maintenance = await category(householdOther.id, "Maintenance");

  // ---------------------------------------------------------------------------
  // Reset GENERATED activity
  //
  // Importantly:
  // - recurring transactions themselves are NOT touched
  // - transactions generated by recurring transactions are NOT touched
  //
  // This makes `prisma db seed` reasonably safe to execute repeatedly.
  // ---------------------------------------------------------------------------

  await prisma.$transaction([
    prisma.transaction.deleteMany({
      where: {
        recurringTransactionId: null,

        wallet: {
          workspaceId: {
            in: [personalWorkspace.id, householdWorkspace.id],
          },
        },
      },
    }),

    prisma.transfer.deleteMany({
      where: {
        OR: [
          {
            fromWallet: {
              workspaceId: {
                in: [personalWorkspace.id, householdWorkspace.id],
              },
            },
          },
          {
            toWallet: {
              workspaceId: {
                in: [personalWorkspace.id, householdWorkspace.id],
              },
            },
          },
        ],
      },
    }),
  ]);

  // ---------------------------------------------------------------------------
  // Transaction helper
  // ---------------------------------------------------------------------------

  type SeedTransaction = {
    amount: string | number;
    walletId: number;
    categoryId: number;
    createdById: number;
    occurredAt: Date;
  };

  const transactions: SeedTransaction[] = [];

  function addTransaction(transaction: SeedTransaction) {
    transactions.push(transaction);
  }

  // ---------------------------------------------------------------------------
  // Six months of personal history
  // ---------------------------------------------------------------------------

  for (let month = 5; month >= 0; month--) {
    // Salary
    addTransaction({
      amount: "2850.00",
      walletId: personalBank.id,
      categoryId: salary.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 1, 9),
    });

    // Rent
    addTransaction({
      amount: "850.00",
      walletId: personalBank.id,
      categoryId: rent.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 2),
    });

    // Utilities fluctuate month-to-month.
    addTransaction({
      amount: (75 + (month % 3) * 12).toFixed(2),
      walletId: personalBank.id,
      categoryId: utilities.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 6),
    });

    // Subscriptions
    addTransaction({
      amount: "12.99",
      walletId: personalCreditCard.id,
      categoryId: subscriptions.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 4),
    });

    addTransaction({
      amount: "9.99",
      walletId: personalCreditCard.id,
      categoryId: subscriptions.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 14),
    });

    // Groceries
    const groceryAmounts = [54 + month, 37 + month * 1.5, 71 - month, 46 + month];

    const groceryDays = [5, 11, 18, 25];

    groceryAmounts.forEach((amount, index) => {
      addTransaction({
        amount: amount.toFixed(2),
        walletId: index === 2 ? personalCash.id : personalCreditCard.id,
        categoryId: groceries.id,
        createdById: alex.id,
        occurredAt: monthsAgo(month, groceryDays[index], 18),
      });
    });

    // Dining
    addTransaction({
      amount: (18 + month * 2.3).toFixed(2),
      walletId: personalCreditCard.id,
      categoryId: dining.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 8, 20),
    });

    addTransaction({
      amount: (31 + month).toFixed(2),
      walletId: personalCreditCard.id,
      categoryId: dining.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 21, 21),
    });

    // Transportation
    addTransaction({
      amount: (48 + month * 1.75).toFixed(2),
      walletId: personalCreditCard.id,
      categoryId: fuel.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 10),
    });

    addTransaction({
      amount: "27.00",
      walletId: personalBank.id,
      categoryId: publicTransport.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 3),
    });

    if (month % 2 === 0) {
      addTransaction({
        amount: (13 + month).toFixed(2),
        walletId: personalCreditCard.id,
        categoryId: taxi.id,
        createdById: alex.id,
        occurredAt: monthsAgo(month, 19, 23),
      });
    }

    // Lifestyle
    addTransaction({
      amount: (24 + month * 4).toFixed(2),
      walletId: personalCreditCard.id,
      categoryId: entertainment.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 16, 20),
    });

    if (month % 2 === 1) {
      addTransaction({
        amount: (65 + month * 8).toFixed(2),
        walletId: personalCreditCard.id,
        categoryId: shopping.id,
        createdById: alex.id,
        occurredAt: monthsAgo(month, 22),
      });
    }

    // Health
    if (month === 1 || month === 4) {
      addTransaction({
        amount: "22.50",
        walletId: personalBank.id,
        categoryId: pharmacy.id,
        createdById: alex.id,
        occurredAt: monthsAgo(month, 13),
      });
    }

    // Small bank fee
    addTransaction({
      amount: "3.00",
      walletId: personalBank.id,
      categoryId: bankFees.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 28),
    });
  }

  // ---------------------------------------------------------------------------
  // Irregular personal transactions
  // ---------------------------------------------------------------------------

  addTransaction({
    amount: "650.00",
    walletId: personalBank.id,
    categoryId: freelance.id,
    createdById: alex.id,
    occurredAt: monthsAgo(4, 17),
  });

  addTransaction({
    amount: "420.00",
    walletId: personalBank.id,
    categoryId: freelance.id,
    createdById: alex.id,
    occurredAt: monthsAgo(1, 24),
  });

  addTransaction({
    amount: "750.00",
    walletId: personalBank.id,
    categoryId: bonus.id,
    createdById: alex.id,
    occurredAt: monthsAgo(2, 1),
  });

  addTransaction({
    amount: "4.72",
    walletId: personalSavings.id,
    categoryId: interest.id,
    createdById: alex.id,
    occurredAt: monthsAgo(1, 28),
  });

  addTransaction({
    amount: "85.00",
    walletId: personalBank.id,
    categoryId: doctor.id,
    createdById: alex.id,
    occurredAt: monthsAgo(3, 12),
  });

  addTransaction({
    amount: "328.40",
    walletId: personalCreditCard.id,
    categoryId: travel.id,
    createdById: alex.id,
    occurredAt: monthsAgo(2, 18),
  });

  // ---------------------------------------------------------------------------
  // Household history
  // ---------------------------------------------------------------------------

  for (let month = 5; month >= 0; month--) {
    // Contributions from Alex and Maria.
    addTransaction({
      amount: "650.00",
      walletId: householdJoint.id,
      categoryId: contribution.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 1, 8),
    });

    addTransaction({
      amount: "650.00",
      walletId: householdJoint.id,
      categoryId: contribution.id,
      createdById: maria.id,
      occurredAt: monthsAgo(month, 1, 10),
    });

    addTransaction({
      amount: "900.00",
      walletId: householdJoint.id,
      categoryId: householdRent.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 2),
    });

    addTransaction({
      amount: (82 + month * 4).toFixed(2),
      walletId: householdJoint.id,
      categoryId: electricity.id,
      createdById: maria.id,
      occurredAt: monthsAgo(month, 9),
    });

    addTransaction({
      amount: "34.90",
      walletId: householdJoint.id,
      categoryId: internet.id,
      createdById: alex.id,
      occurredAt: monthsAgo(month, 12),
    });

    // Shared groceries
    for (const [index, day] of [4, 11, 18, 25].entries()) {
      addTransaction({
        amount: (45 + index * 7 + month * 1.5).toFixed(2),
        walletId: index === 3 ? householdCash.id : householdJoint.id,
        categoryId: householdGroceries.id,
        createdById: index % 2 === 0 ? alex.id : maria.id,
        occurredAt: monthsAgo(month, day, 18),
      });
    }

    if (month % 2 === 0) {
      addTransaction({
        amount: (38 + month * 3).toFixed(2),
        walletId: householdJoint.id,
        categoryId: householdSupplies.id,
        createdById: maria.id,
        occurredAt: monthsAgo(month, 20),
      });
    }
  }

  addTransaction({
    amount: "145.00",
    walletId: householdJoint.id,
    categoryId: maintenance.id,
    createdById: alex.id,
    occurredAt: monthsAgo(3, 16),
  });

  addTransaction({
    amount: "78.50",
    walletId: householdJoint.id,
    categoryId: maintenance.id,
    createdById: maria.id,
    occurredAt: monthsAgo(0, 7),
  });

  // ---------------------------------------------------------------------------
  // Insert transactions
  // ---------------------------------------------------------------------------

  await prisma.transaction.createMany({
    data: transactions.map((transaction) => ({
      ...transaction,
      amount: d(transaction.amount),
    })),
  });

  // ---------------------------------------------------------------------------
  // Transfers
  //
  // Transfers are deliberately kept separate from income/expenses.
  // ---------------------------------------------------------------------------

  await prisma.transfer.createMany({
    data: [
      // Build personal savings over time.
      ...Array.from({ length: 6 }, (_, index) => {
        const month = 5 - index;

        return {
          amount: d("300.00"),
          fromWalletId: personalBank.id,
          toWalletId: personalSavings.id,
          createdById: alex.id,
          occurredAt: monthsAgo(month, 3),
        };
      }),

      // Withdraw cash periodically.
      {
        amount: d("100.00"),
        fromWalletId: personalBank.id,
        toWalletId: personalCash.id,
        createdById: alex.id,
        occurredAt: monthsAgo(4, 7),
      },
      {
        amount: d("120.00"),
        fromWalletId: personalBank.id,
        toWalletId: personalCash.id,
        createdById: alex.id,
        occurredAt: monthsAgo(2, 7),
      },
      {
        amount: d("100.00"),
        fromWalletId: personalBank.id,
        toWalletId: personalCash.id,
        createdById: alex.id,
        occurredAt: monthsAgo(0, 7),
      },

      // Household emergency fund.
      {
        amount: d("200.00"),
        fromWalletId: householdJoint.id,
        toWalletId: householdSavings.id,
        createdById: alex.id,
        occurredAt: monthsAgo(4, 27),
      },
      {
        amount: d("200.00"),
        fromWalletId: householdJoint.id,
        toWalletId: householdSavings.id,
        createdById: maria.id,
        occurredAt: monthsAgo(2, 27),
      },
      {
        amount: d("250.00"),
        fromWalletId: householdJoint.id,
        toWalletId: householdSavings.id,
        createdById: alex.id,
        occurredAt: monthsAgo(0, 27),
      },

      // Household cash withdrawal.
      {
        amount: d("150.00"),
        fromWalletId: householdJoint.id,
        toWalletId: householdCash.id,
        createdById: maria.id,
        occurredAt: monthsAgo(1, 5),
      },
    ],
  });

  // ---------------------------------------------------------------------------
  // Summary
  // ---------------------------------------------------------------------------

  const [
    userCount,
    workspaceCount,
    walletCount,
    typeCount,
    categoryCount,
    transactionCount,
    transferCount,
    recurringCount,
  ] = await Promise.all([
    prisma.user.count(),
    prisma.workspace.count(),
    prisma.wallet.count(),
    prisma.transactionType.count(),
    prisma.transactionCategory.count(),
    prisma.transaction.count(),
    prisma.transfer.count(),
    prisma.recurringTransaction.count(),
  ]);

  console.log("");
  console.log("✅ Seed completed");
  console.log(`   Users:                  ${userCount}`);
  console.log(`   Workspaces:             ${workspaceCount}`);
  console.log(`   Wallets:                ${walletCount}`);
  console.log(`   Transaction types:      ${typeCount}`);
  console.log(`   Categories:             ${categoryCount}`);
  console.log(`   Transactions:           ${transactionCount}`);
  console.log(`   Transfers:              ${transferCount}`);
  console.log(`   Recurring transactions: ${recurringCount}`);
  console.log("");
}

main()
  .catch((error) => {
    console.error("❌ Seed failed:");
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
